### ISSUE TITLE
TagsRoutes not working

### ISSUE THREAD

**Issue by RealSourceOfficial** [kctekn/obsidian-TagsRoutes#14]
**Describe the bug**
Appears that TagsRoutes is entirely dead? Not sure the issue, thought I'd let you know. I'm newer to obsidian, no expert but I know my way around - knew something was up when I enabled the plugin and nothing showed up. Got a logs folder and reports folder, both are empty.

**To Reproduce**
1. Install TagsRoutes
2. Enable TagsRoutes
3. Plugin does not show up app-wide

- OS: Windows 11
- Obsidian: 1.6.7
- Plugin: 1.0.9 (Installed via plugin browser, if it matters)

**Screenshots**
![image](https://github.com/user-attachments/assets/3436ea5c-e388-4dc6-b640-a5455e4ef619)  ![image](https://github.com/user-attachments/assets/f5fecb10-cfec-43ad-83e9-cd09483c8815)  ![image](https://github.com/user-attachments/assets/55dfac54-3766-4d84-a28d-783ae9d217b8)  ![image](https://github.com/user-attachments/assets/e0b924f7-cea9-4b7b-b34e-4ef567a5752f)

**Comment by kctekn** [comment]
Not sure what is happening, you should can find a ribbon button on the left:
![image](https://github.com/user-attachments/assets/f6353fd9-0a55-4124-a7de-0a794c7d33bf)
In Windows system, you can press ctrl-shift-I to toggle to show the dev panel, and check console: is there anything message there?

**Comment by RealSourceOfficial** [comment]
On load it gives this error
![image](https://github.com/user-attachments/assets/a710eb57-c130-4c33-ab12-7f5f4092b1f0)

**Comment by kctekn** [comment]
It should be the new added variable issue, maybe you are the first time to install? I'm so sorry about that, please check attach version:
>>>>  [main_ver109fix.zip](https://github.com/user-attachments/files/16858802/main_ver109fix.zip)
- Unzip to main.js and put it into your vault_directory/.obsidian/plugins/tags-routes, override the original one

**Comment by kctekn** [comment]
I released version 1.0.10 for this fix, so you can update it directly from obsidian plugin manager now!

**Comment by RealSourceOfficial** [comment]
Thank you lol, I have obsidian installed on iOS and doing that would be much harder... will report back if anything else comes up.
