### ISSUE TITLE
Scrollbar "flicker" when in a sidebar

### ISSUE THREAD

**Issue by ShaneNZ** [kctekn/obsidian-TagsRoutes#2]
I have a rendering issue when I put the window into the sidebar:

https://github.com/user-attachments/assets/6a0b6e09-a472-46df-aba0-a413db6e62ec

As you can see, the flickering/movement is coming from the scrollbars being added/removed repeatedly. Zooming/panning/scrolling doesn't affect or impact it in any way, nor does resizing the Obsidian window change anything. Both horizontal and vertical scrollbars are being added/removed.

I'm using the minimal theme by the way, but I get the same behaviour in the default theme as well. Have tested with all other plugins and snippets disabled: still get the flickering.

Console is logging this (not sure if it's relevant or not):

<img width="289" alt="image" src="https://github.com/user-attachments/assets/f9890773-3780-4a84-91cc-7f8931782c56">

**Comment by ShaneNZ** [comment]
Have just noticed that the same thing sometimes does happen when opening in the main area - in the sidebar it happens 100% of the time, but the same behaviour seems to be intermittent but present in the main tab area as well.

**Comment by kctekn** [comment]
please try add this to to `style.css` under  .plugins/obsidian-tags-routes:
```css
.tags-routes .graph-container{
    overflow: hidden !important;
}
```
it might help on this.

**Comment by ShaneNZ** [comment]
Added it via a snippet, problem solved. Thank you!
