### ISSUE TITLE
Disabling of Logs/Reports Folder

### ISSUE THREAD

**Issue by Ronniie** [kctekn/obsidian-TagsRoutes#21]
**Is your feature request related to a problem? Please describe.**
I like my Obsidian Vault very clean, but with TagRoutes, it creates a folder named "TagsRoutes"; with logs, and reports.

**Describe the solution you'd like**
I'd like for it not to create folders at all. The solution could be a very simple toggle for users debugging on why something isn't working. I do not need logs at this moment.

**Describe alternatives you've considered**
Modifying the plugin myself to remove this, or deleting the folder on startup. Potentially even a bash script to detect, and auto-remove lol.

**Additional context**
It'd be very nice to have the option if we want logs/error reports, I understand the use of it for sure and do not want it to go away; I just want it at least hidden, or as an option.

**Comment by kctekn** [comment]
Thanks for you feedback! Currently if you click on a tag node, it will generate a note to TagsRoutes/reports, which contains the query result, and also with the "tags routes" code block. So you can read this report later on even you don't open the TagsRoutes scene. This is a facilitate to get the information of tags, or frontmatter tags:  no need to write the query code in ``` ``` code block, but with a mouse click. If no folder is used, this feature will not work. So currently the folder existance is necessary. Maybe we can add an option to customize the folder location, allowing you to place them in a folder of your choice. For the logs, actully you can turn off the log update and display in the plugin's settings tab.

**Comment by Ronniie** [comment]
Thanks for the quick reply. That's a good idea. Adding onto the customization of the folder location, adding a period to the folder makes it hidden from the folder pane. If the folder is truly needed for the functionality, I never looked at query results myself, the option could be to just add a period or put it into .obsidian?

**Comment by kctekn** [comment]
It seems that obsidian will not read files in a hidden folder, so that it might can't be done in this way :-(

**Comment by Ronniie** [comment]
Seriously? That sucks. I'll try playing around with it on my end this weekend and submit a PR if I can get it working as I really do not like the folder 🤣

**Comment by kctekn** [comment]
Yes, Obsidian currently doesn't reveal notes in hidden folders; it seems to be intended behavior.

**Comment by kctekn** [comment]
Please refer to the new version: https://github.com/kctekn/obsidian-TagsRoutes/releases/tag/1.1.3

**Comment by Ronniie** [comment]
That works perfectly, thank you! 😄
