### ISSUE TITLE
LMB+Drag and RMB+Drag has no effect (3D graph neither rotates nor pans)

### ISSUE THREAD

**Issue by freegemini** [kctekn/obsidian-TagsRoutes#34]
**Describe the bug**
After activating the plugin, rotation and panning do not work. I tried `LMB/RMB+Drag` + variations with `Ctrl`, `Alt`, `Shift`, 'Ctrl+Alt`, `Ctrl+Shift`, `Alt+Shift`. It didn't help

**To Reproduce**
1. Go to any page in vault
2. Click on 'Open tags routes' icon 
3. When tab with 3D Graph opens - LMB/RMB+Drag on it
4. Nothing happens: No rotation. No panning

**Expected behavior**
I expected: 3d-rotation of graph, when selecting node - travelling to this node. The only thing that works is - travelling to the selected node. But it was not possible to achieve rotation around this node.

**Screenshots**
https://github.com/user-attachments/assets/dfa1ca8a-db02-4800-a9f9-2200288a7d47

**Desktop (please complete the following information):**
 - OS: Win10 22H2 19045.5011
 - Browser: Opera 114.0.5282.222

**Additional context**
Also tried to uninstall/install plugin

**Comment by kctekn** [comment]
Thanks for the feedback! This is really a issue that I have not noticed before. I'm checking with that, and for the moment there is a workaround here: 
1. After you have clicked on the TagsRoutes icon, the page opened: but you cannot rotate it.
2. Close Obsidian directly
3. Open Obsidian again: the TagsRoutes page will be opened automatically in last place: no need to click on the icon again.
4. Now everthing seems OK: rotation is functional as normal.
For the issue, I'm checking with that and maybe fix it in the next release.

**Comment by kctekn** [comment]
This bug has been fixed: you can update to release [1.2.2](https://github.com/kctekn/obsidian-TagsRoutes/releases/tag/1.2.2) now.
